version: 1.0.{build}
image:
    - Visual Studio 2017
    - Ubuntu
test: off
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build_script:
    - cmd: build.bat canary skipdocs

nuget:
    disable_publish_on_pr: true

for:

    - branches:
          only:
              - /^(master|\d+\.x)$/
      artifacts:
          - path: .\build\output\_packages\*.nupkg
            name: NuGet

    -
        matrix:
            only:
                - image: Ubuntu

        build_script:
            - ./build.sh test-one skipdocs
